config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  scope module: :v1, constraints: ApiConstraints.new(version: "1", default: true), defaults: { format: :html } do
    root :to => 'root#index'

    namespace :accounts do
        scope :login do
            get '' => :'login', as: :login
        end
        scope :logedin do
            post '' => :'logedin', as: :logedin
        end
        scope :logout do
            get '' => :'logout', as: :logout
        end
    end

    resources :search, only: [:index, :show, :search]
    resources :roles

    resources :users
    resources :projects
    resources :project_messages
    resources :project_users
    resources :teams
    resources :team_messages
    resources :team_users




    # scope :users do
    #   users get    ''                     => 'users#index',                                 as: :users_index
    #   get    ':major,:minor'        => 'users#show_by_major_and_minor',               as: :users_show_by_major_and_minor
    #   get    ':major,:minor/kanban' => 'users#show_by_major_and_minor_within_kanban', as: :users_show_by_major_and_minor_within_kanban
    #   user get    ':id'                  => 'users#show',                                  as: :users_show
    #   post   ''                     => 'users#create',                                as: :users_create
    #   put    ''                     => 'users#update',                                as: :users_update
    #   delete ''                     => 'users#destroy',                               as: :users_destroy
    # end

  end
end

app/controllers/v1/accounts_controller.rb
class V1::AccountsController < V1::BaseController

  def login
    new
  end

  # login
  def logedin
    if login_account(params[:account][:provider], params[:account][:uid])
      redirect_to controller: 'users', action: 'show', id: @logedin_user.id

    else
      flash[:error] = "failed login"
      redirect_to accounts_login_path

    end
  end

  # logout
  def logout
    logout_account
    redirect_to root_path
  end

end

app/controllers/v1/base_controller.rb
class V1::BaseController < ApplicationController
  include Restable
end

app/controllers/v1/project_messages_controller.rb
class V1::ProjectMessagesController < V1::BaseController

  def new
    model_instance = new_model
    model_instance.users << @logedin_user
    common_new(model_instance)
  end

  def create
    result, model_instance = create_model(params)
    model_instance.save
    redirect_to controller: 'projects', action: 'show', id: model_instance.project.id

  end

end

app/controllers/v1/project_users_controller.rb
class V1::ProjectUsersController < V1::BaseController

  def new
    model_instance = new_model
    model_instance.users << @logedin_user
    common_new(model_instance)
  end

  def create
    result, model_instance = create_model(params)
    model_instance.save
    redirect_to controller: 'projects', action: 'show', id: model_instance.project.id

  end

end

app/controllers/v1/projects_controller.rb
class V1::ProjectsController < V1::BaseController

  def show

    model_instance = get_model({id: params[:id]})
    unless contains_current_user?(@project)
      super
      return
    end

    @project = Project.preload(:users).find(params[:id])
    @timeline = Timeline.new
    @timeline.add_project(@project)

    @new_message = ProjectMessage.new
    @new_message.user = @logedin_user
    @new_message.project = @project

    common_show model_instance
  end

end

app/controllers/v1/roles_controller.rb
class V1::RolesController < V1::BaseController


  def show
    @roles = Role.all
    @role = Role.find_by({id: params[:id]})
    @joined_role = Role.includes(:users).find_by({id: params[:id], users: {scope: "public"}})
    # @role = Role.preload(:users).where(id: params[:id])

    # @role = Role.find_by(id: params[:id])
    # @role.users.where(scope: "public").each do |user|
    #   p user.id
    # end

    model_instance = @role
    common_show model_instance
  end

end

app/controllers/v1/rooms_controller.rb
class V1::RoomsController < V1::BaseController

  def new
    model_instance = new_model
    model_instance.users << @logedin_user
    common_new(model_instance)
  end

  def create
    result, model_instance = create_model(params)
    model_instance.users << @logedin_user
    model_instance.save
    redirect_to action: 'show', id: model_instance.id

  end

end

app/controllers/v1/root_controller.rb
class V1::RootController < ApplicationController

  def index
    respond_to do |format|
      format.html # html
      format.json { render json: model_instance } # json
    end
  end

end

app/controllers/v1/search_controller.rb
class V1::SearchController < ApplicationController

  def index
    search params[:search]

    respond_to do |format|
      format.html # html
      format.json { render json: model_instance } # json
    end
  end

  def show
    search params[:search]

    respond_to do |format|
      format.html # html
      format.json { render json: model_instance } # json
    end

  end

  def search(search)

    if search
      @users      = User.where(['name LIKE ?',    "%#{search}%"])
      @projects   = Project.where(['name LIKE ?', "%#{search}%"])
      @teams      = Team.where(['name LIKE ?',    "%#{search}%"])

    else
      @users      = User.where(['name LIKE ?',    "%#{search}%"])
      @projects   = Project.where(['name LIKE ?', "%#{search}%"])
      @teams      = Team.where(['name LIKE ?',    "%#{search}%"])

    end

  end


end

app/controllers/v1/team_messages_controller.rb
class V1::TeamMessagesController < V1::BaseController

  def new
    model_instance = new_model
    model_instance.users << @logedin_user
    common_new(model_instance)
  end

  def create
    result, model_instance = create_model(params)
    model_instance.save
    redirect_to controller: 'teams', action: 'show', id: model_instance.team.id

  end

end

app/controllers/v1/team_users_controller.rb
class V1::TeamUsersController < V1::BaseController

  def new
    model_instance = new_model
    model_instance.users << @logedin_user
    common_new(model_instance)
  end

  def create
    result, model_instance = create_model(params)
    model_instance.save
    redirect_to controller: 'projects', action: 'show', id: model_instance.project.id

  end

end

app/controllers/v1/teams_controller.rb
class V1::TeamsController < V1::BaseController

  def new
    model_instance = new_model
    model_instance.users << @logedin_user
    common_new(model_instance)
  end

  def create
    result, model_instance = create_model(params)
    model_instance.users << @logedin_user
    model_instance.save
    redirect_to action: 'show', id: model_instance.id

  end


  def index
    @teams = Team.where(scope: "public")
    model_instances = @teams
    common_index model_instances
  end

  def show

    model_instance = get_model({id: params[:id]})
    unless contains_current_user?(@team)
      super
      return
    end

    @team = Team.preload(:users).find(params[:id])
    @timeline = Timeline.new
    @timeline.add_team(@team)

    @new_message = TeamMessage.new
    @new_message.user = @logedin_user
    @new_message.team = @team

    common_show model_instance
  end


end

app/controllers/v1/users_controller.rb
class V1::UsersController < V1::BaseController

  def etid
    unless current_user?
      home
      return
    end

    @user = User.preload(:roles, :teams, :projects).find(@logedin_user.id)
    model_instance = @user
    common_edit(model_instance)
  end

  def update
    unless current_user?
      home
      return
    end

    @user = User.preload(:roles, :teams, :projects).find(@logedin_user.id)
    if @user.update_roles(params)
      p "roles_updated!"
      # @user.reload
    end

    result, model_instance = update_model(@user, params)
    if result
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    unless current_user?
      super
      return
    end

    user_id = params[:id]
    @user = User.preload(:roles, :teams, :projects).find(user_id)
    model_instance = @user

    p "debug : " + @user.detail
    # p "debug"
    # @user.teams.each { |team|
    #   team.team_messages.each { |message|
    #     p "message : #{message.to_s}"
    #     p "message : #{message.text}"
    #   }
    # }

    @timeline = Timeline.new
    @timeline.add_user(@user)
    # p "messages : #{@messages.to_s}"
    # @messages.each do |message|
    #   p "message : #{message.user}"

    # end

    # @user.each do |user|
    #   p "user : #{user.to_s}"
    #   p "user name : #{user.name}"
    #   user.teams.each do |team|
    #     p "team name: #{team.name}"
    #   end
    # end

    common_show model_instance
  end

  def show_by_major_and_minor_within_kanban
    @within_kanban = true
    model_instance = get_model(:major => params[:major], :minor => params[:minor])
    common_show model_instance
  end

end

app/views/v1/share/_container.html.slim
div class="container theme-showcase" role="main"
  div class="column_center col-md-12"
    == yield

  div class="column_left col-md-3"
    == yield(:column_left)

  div class="column_center col-md-6"
    == yield(:column_center)

  div class="column_right col-md-3"
    == yield(:column_right)

app/views/v1/share/_footer.html.slim
hr
footer
  p Indies

app/views/v1/share/_grid_projects.html.slim
- if local_assigns.has_key? :projects
  - column = 0
  div class="grid-projects"
    <div class="row">
    - projects.each do |item|
      - column = column + 1
      - if 3 < column
        </div>
        <div class="row">
        - column = 1

      div class="col-md-3"
        = link_to item do
          = image_tag 'default-placeholder.png', alt: item.name, size: '64x64', class: 'thumbnail'


    </div>

app/views/v1/share/_grid_users.html.slim
- if local_assigns.has_key? :users
  - column = 0
  div class="grid-users"
    <div class="row">
    - users.each do |item|
      - column = column + 1
      - if 3 < column
        </div>
        <div class="row">
        - column = 1

      div class="col-md-3"
        = link_to item do
          = image_tag 'default-placeholder.png', alt: item.name, size: '64x64', class: 'thumbnail'


    </div>

app/views/v1/share/_header.html.slim
nav class="navbar navbar-default navbar-fixed-top" role="navigation"
  div class="container"
    div class="navbar-header"
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span class="sr-only" Toggle navigation
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"
      = link_to 'Indies', root_path, { class: "navbar-brand" }
    div id="navbar" class="navbar-collapse collapse"
      ul class="nav navbar-nav"
        li
          form method='get' action='/search' class="navbar-form"
            div class="form-group"
              input type='text' placeholder='user / team / project' class="form-control"
            input type='submit' value='search' class="btn"

        li = link_to 'users', users_path
        li = link_to 'teams', teams_path
        li = link_to 'projects', projects_path

        - if nil != @logedin_user
          li class="dropdown"
            a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
              = @logedin_user.name
              span class="caret"
            ul class="dropdown-menu" role="menu"
              li = link_to 'profile', @logedin_user
              li class="divider"
              li = link_to 'settings', edit_user_path(@logedin_user.id)
              li = link_to 'logout', accounts_logout_path
        - else
          li = link_to 'login',  accounts_login_path

app/views/v1/share/_index_messages.html.slim
- if local_assigns.has_key? :messages
  table
    thead
      tr
        th from
        th text
        th updated_at
        th to
    tbody
      - messages.each do |item|
        tr
          td = link_to item.user.name, item.user
          td = item.text
          td = item.updated_at

          - if item.room.present?
            - to_item = item.room
          - elsif item.team.present?
            - to_item = item.team
          - elsif item.project.present?
            - to_item = item.project

          - if defined?(to_item)
            td = link_to to_item.name, to_item
          - else
            td -

app/views/v1/share/_index_team_projects.html.slim
- if team_projects.present?
  table
    thead
      tr
        th Id
        th Name
        th Picture
        th CreatedAt
        th UpdatedAt
        th
        th TeamId
        th TeamName
    tbody
      - team_projects.each do |team, projects|
        - projects.each do |project|
          tr
            td = project.id
            td = project.name
            td = project.picture
            td = project.created_at
            td = project.updated_at
            td = link_to 'Show', project
            - if team.present?
              td  = team.id
              td  = team.name
            - else
              td -
              td -

app/views/v1/share/_index_team_users.html.slim
- if team_users.present?
  table
    thead
      tr
        th Id
        th Name
        th Picture
        th CreatedAt
        th UpdatedAt
        th
        th TeamId
        th TeamName
    tbody
      - team_users.each do |team, users|
        - users.each do |user|
          tr
            td = user.id
            td = user.name
            td = user.picture
            td = user.created_at
            td = user.updated_at
            td = link_to 'Show', user
            - if team.present?
              td  = team.id
              td  = team.name
            - else
              td -
              td -

app/views/v1/share/_index_teams.html.slim
- if local_assigns.has_key? :teams
  table class="table table-striped"
    thead
      tr
        th id
        th name
        th picture
        th created_at
        th updated_at
        th
    tbody
      - teams.each do |team|
        tr
          td = team.id
          td = team.name
          td = team.picture
          td = team.created_at
          td = team.updated_at
          td = link_to 'Show', team

app/views/v1/share/_index_timeline.html.slim
- if local_assigns.has_key? :timeline
  table class="table table-striped"
    thead
      tr
        th from
        th text
        th updated_at
        th to
    tbody
      - timeline.messages.each do |item|
        tr
          td = link_to item.user.name, item.user
          td = item.text
          td = item.updated_at

          - if defined? item.team
            - to_item = item.team
          - elsif defined? item.project
            - to_item = item.project

          - if defined?(to_item)
            td = link_to to_item.name, to_item
          - else
            td -

app/views/v1/share/_index_users.html.slim
- if local_assigns.has_key? :users
  table class="table table-striped"
    thead
      tr
        th id
        th name
        th picture
        th created_at
        th updated_at
        th
    tbody
      - users.each do |user|
        tr
          td = user.id
          td = user.name
          td = user.picture
          td = user.created_at
          td = user.updated_at
          td = link_to 'Show', user

app/views/v1/share/_show_project.html.slim
ul
  li = project.id
  li = project.name
  li = project.picture
  li = project.created_at
  li = project.updated_at

- if local_assigns.has_key? :users
  h3 Members
  = share_render('index_users', {users: users})

app/views/v1/share/_show_team.html.slim
ul
  li = team.id
  li = team.name
  li = team.picture
  li = team.created_at
  li = team.updated_at

- if local_assigns.has_key? :users
  h3 Members
  = share_render('index_users', {users: users})

- if local_assigns.has_key? :projects
  h3 Projects
  = share_render('index_projects', {projects: projects})

app/views/v1/share/_show_user.html.slim
div class="row"
  div class="col-md-1"
    = link_to user do
      = user.name
      = image_tag 'default-placeholder.png', alt: user.name, size: '96x96', class: 'thumbnail'
div class="row"
  - user.roles.each do |role|
    = link_to role.name, role, class: "btn btn-info btn-xs"

- if (local_assigns.has_key? :teams) && (teams.present?)
  h4 Teams
  = share_render('grid_teams', {teams: teams})
  - if current_user?
    p = link_to 'Create New Team',    new_team_path

- if (local_assigns.has_key? :projects) && (projects.present?)
  h4 Projects
  = share_render('grid_projects', {projects: projects})
  - if current_user?
    p = link_to 'Create New Project', new_project_path